### ISSUE TITLE
Code cannot work properly .

### ISSUE THREAD

**Issue by jun99999** [kontaktio/kontakt-beacon-admin-sample-app#17]
Hello, may I know what steps I missed, I have lots of errors after I import the sample coding in android studio.
![image](https://cloud.githubusercontent.com/assets/20786078/17316608/1915e4a4-58a8-11e6-8506-bc3524aacd4c.png)
![image](https://cloud.githubusercontent.com/assets/20786078/17316629/2b45c554-58a8-11e6-93f3-2df2aacc0ea8.png)

**Comment by michaldrabik** [comment]
Seems like a Android Studio/Gradle issue. Try cleaning the project (Build -> Clean Project) or invalidating cache (File -> Invalidate Caches/Restart)

**Comment by jun99999** [comment]
Thanks for your suggestions, however after I restart and clean it. Still looks same. Do you mind help me in teamviewer?

![image](https://cloud.githubusercontent.com/assets/20786078/17318513/88cfa9ea-58b9-11e6-9915-a89defe36755.png)
![image](https://cloud.githubusercontent.com/assets/20786078/17318526/99b8b558-58b9-11e6-97c7-91b30a4855b4.png)
![image](https://cloud.githubusercontent.com/assets/20786078/17318533/a74da85e-58b9-11e6-8a02-1859b6c3477d.png)
![image](https://cloud.githubusercontent.com/assets/20786078/17318537/ae37d2de-58b9-11e6-81f1-b1c7174f32d9.png)

![image](https://cloud.githubusercontent.com/assets/20786078/17318547/ba531164-58b9-11e6-841d-010a23272215.png)

**Comment by michaldrabik** [comment]
Seems like androidToolsVersion variable is missing as stated in the error message. Check out this project's build.gradle [HERE](https://github.com/kontaktio/kontakt-beacon-admin-sample-app/blob/master/sample-app-module/build.gradle) and use it in your project.

**Comment by jun99999** [comment]
Hello, I paste the coding to the page, but keep showing the build.gardle problem.

![image](https://cloud.githubusercontent.com/assets/20786078/17318817/e0edd2c6-58bb-11e6-9e03-98c8b189bf59.png)
![image](https://cloud.githubusercontent.com/assets/20786078/17318822/f48b7ffe-58bb-11e6-8af7-3919779ff697.png)

**Comment by jun99999** [comment]
![image](https://cloud.githubusercontent.com/assets/20786078/17318868/4d53e5ea-58bc-11e6-8532-cee806198b4e.png)
![image](https://cloud.githubusercontent.com/assets/20786078/17318878/60011c08-58bc-11e6-87c6-1ca87c3cf0ab.png)
![image](https://cloud.githubusercontent.com/assets/20786078/17318886/6d9cfb34-58bc-11e6-8488-6b31fa2587a6.png)

I think there have some problems with the SDK

**Comment by michaldrabik** [comment]
It's not SDK problem but with the gradle file. You are missing `packagingOptions` in android {} tag: 

```
android {
    compileSdkVersion 23
    buildToolsVersion '23.0.3'

    defaultConfig {
        applicationId "com.kontakt.sample"
        minSdkVersion 18
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }

    packagingOptions {
        exclude 'main/AndroidManifest.xml'
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}
```

**Comment by jun99999** [comment]
![image](https://cloud.githubusercontent.com/assets/20786078/17318942/d0a5ff32-58bc-11e6-9dff-5d302648d652.png)
 I have it just not screenshot completed.

**Comment by jun99999** [comment]
Hello sir
This is my teamviewer, if you are free, very welcome to help me.
940 035 501
2168
Thank you

Best regards
Jun

**Comment by michaldrabik** [comment]
Sorry I don't have time for TeamViewer etc. Can you share this project with me somehow? Upload to Github or send me a .zip archive. It'll be faster and easier that way.

**Comment by jun99999** [comment]
Thanks for your kindness, [image: Inline image 1]

I upload to the Google Driver. You can download here.

**Comment by michaldrabik** [comment]
@jun99999 Can't see any link.

**Comment by jun99999** [comment]
https://drive.google.com/drive/my-drive 

![image](https://cloud.githubusercontent.com/assets/20786078/17319416/0a96d060-58c0-11e6-872d-85bfd2c2d19e.png)

you click the share with me.

**Comment by michaldrabik** [comment]
Didn't get anything. I guess you need to right-click the archive and use Share or Get Sharable Link option.

**Comment by jun99999** [comment]
https://drive.google.com/a/elixirtech.com/file/d/0B7CgiPXFfmZ3OE0tS0ttQk9QLUU/view?usp=sharing

**Comment by michaldrabik** [comment]
@jun99999 https://drive.google.com/open?id=0B-sOINpYt_YMcGcwQ2FCQ095Y2s 
Fixed gradle errors. It now builds ok on my computer but there are still some layouts missing. I guess you need to add them by yourself. Regards

**Comment by jun99999** [comment]
I expressed my great appreciation to you, Thank you so much.

**Comment by jun99999** [comment]
[image: Inline image 1]
sorry for this, after I import yours, in my computer still the same.

**Comment by michaldrabik** [comment]
Then I really don't know how i can be more of a help. My advice would be to start new Android Studio project and add things one by one depending on your needs.

**Comment by jun99999** [comment]
Okay, thank you . May I ask you about the Lambda expression . can I use the
API 19 to support this language in Android studio? Since I only can use the
API24 to compile the code. however the android device only can support
lower API. So I have no idea what to do with this situation.
https://drive.google.com/a/elixirtech.com/file/d/0B7CgiPXFfmZ3NzNUcWJDRml3eVU/view?usp=sharing

By the way can you import my coding and show in your physical android
device?

Best regards
Jun

**Comment by michaldrabik** [comment]
API level has nothing to do with Lambda. Java matters. Unfortunatly Android doesn't fully support Java 8 for now. If you want lambda you need to use something like [Retrolambda](https://github.com/evant/gradle-retrolambda)

**Comment by jun99999** [comment]
Thanks for your guidance, so how to change in my coding?

**Comment by jun99999** [comment]
Good moring Michal, I import the project you help me again. It shows no
error, but cannot run. What should I edit?
[image: Inline image 1]

[image: Inline image 2]

Thank you
